### ISSUE TITLE
Confusion  between jd.to_gregorian and jd.from_gregorian

### ISSUE THREAD

**Issue by Surdaster** [seanredmond/juliandate#2]
%pip install juliandate
import juliandate as jd
jd.to_gregorian(0), jd.from_gregorian(-4713, 11, 24, 12, 0, 0, 0)

The output is:
((-4713, 11, 24, 12, 0, 0, 0), -1.0)

I expected to have 0 instead of -1.0 ... as the requested operations are perfectly symmetrical.
Is there anything unclear with the programs?

**Comment by seanredmond** [comment]
Looking into it

**Comment by Surdaster** [comment]
Nice, thanks!

Will it be implemented soon? so that the updated version will be available simply by using "%pip install juliandate" in a Jupyter notebook program?

**Comment by seanredmond** [comment]
I'm preparing a new version I hope to release today

**Comment by seanredmond** [comment]
v1.0.3 is released and should fix this. Thanks for the report!
