### ISSUE TITLE
ISO 8601 compliance: minutes, seconds, milliseconds shouldn't be negative numbers.

### ISSUE THREAD

**Issue by mindey** [seanredmond/juliandate#5]
juliandate.to_gregorian(-5090751.041666666)
(-18650, 11, 26, 12, -59, -59, -999946)

Then, it means the ISO 8601 string would be:
-18650-11-26 12:-59:-59.-999946+00:00

Which is not a valid string, cause minutes, seconds, milliseconds can't be negative.

**Comment by seanredmond** [comment]
Sorry to take a while to respond. The conversion algorithms aren't intended to work for negative Julian Day Numbers. I might think about raising an error in this case.

**Comment by mindey** [comment]
I see. However, ISO 8601:2004 (sections 3.4.2, 4.1.2.4) supports negative years (adding minus sign in ISO 8601 means B.C.E. ( https://en.wikipedia.org/wiki/ISO_8601#cite_ref-22 )), so, it would be great to support the negative JDs...
